In [1]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

In [71]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

In [14]:
#Opening the HomePage Amazon.com
url='https://www.amazon.in/'
driver.get(url)

time.sleep(2)

In [13]:
search_bar=driver.find_element_by_id('twotabsearchtextbox')
search_bar

In [14]:
search_bar.send_keys('laptops')

In [15]:
search_btn=driver.find_element_by_id('nav-search-submit-button')
search_btn.click()

In [16]:
# scrape all product urls
product_urls = []
start=0
end=18
for page in range(start,end):#for loop for scrapping 18 page
    url=driver.find_elements_by_xpath('//a[@class="a-link-normal a-text-normal"]')       #scraping urls
    for i in url:
        product_urls.append(i.get_attribute("href"))                        #appending the urls in product_urls list
    nxt_button=driver.find_element_by_xpath('//ul[@class="a-pagination"]/li[4]/a')     #scraping the list of buttons from the page
    nxt_button.click()
    time.sleep(2)
    
    #Make empty list
    Review=[]
    Rating=[]
    
for url in product_urls:
    driver.get(url)
    time.sleep(2)
    
    
    #Extracting Review from xpath
    try:
        review=driver.find_element_by_xpath('//div[@class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content"]')
        Review.append(review.text)
    except NoSuchElementException:
        Review.append("-")
    
    time.sleep(1)
    
    #Extracting Rating from xpath
    try:
        rating=driver.find_element_by_xpath('//span[@class="a-size-base a-nowrap"]/span')
        Rating.append(rating.text)
    except NoSuchElementException:
        Rating.append("-")
        
time.sleep(1)
#Make DataFrame
df=pd.DataFrame({'Review':Review,'Rating':Rating})
df.head(5)

                                              Review        Rating
0  Received this yesterday (04/03/2021). Prompt d...  4.3 out of 5
1                                                  -             -
2  I bought this laptop with 8gb of ram and 256GB...  4.2 out of 5
3  The display cracked inside after 2 months and ...  4.2 out of 5
4  Laptop getting hang very much and very much sl...  3.9 out of 5

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 417 entries, 0 to 416
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  417 non-null    object
 1   Rating  417 non-null    object
dtypes: object(2)
memory usage: 6.6+ KB

In [18]:
df.head(36)

                                               Review        Rating
0   Received this yesterday (04/03/2021). Prompt d...  4.3 out of 5
1                                                   -             -
2   I bought this laptop with 8gb of ram and 256GB...  4.2 out of 5
3   The display cracked inside after 2 months and ...  4.2 out of 5
4   Laptop getting hang very much and very much sl...  3.9 out of 5
5   Nice performance, very thin and comfortable. P...  4.2 out of 5
6   Was excited for this laptop until it got deliv...  4.1 out of 5
7   Good display and built quality\nAmazing for da...  4.2 out of 5
8   Ordered this based on immense research. Certai...  4.4 out of 5
9   PROS\n1. Its touch screen\n2. it doesn't have ...  3.8 out of 5
10  Bought this laptop for online classes for my d...  3.9 out of 5
11  Very slim/light and gives the feeling of a pre...    5 out of 5
12                         I received damaged product  4.1 out of 5
13  Before you purchase this, decide whether you c...  4.1 out of 5
14  It heats a lot for basic tasks , i5 i a piece ...  4.5 out of 5
15  1. Great performance on heavy audio editing so...  4.4 out of 5
16  First of all, the product images in amazon are...  3.9 out of 5
17  I love it. The camera feels like 1 mp but the ...  4.2 out of 5
18  Worth in this price ✌🏼I loved the dell ... Tho...  3.7 out of 5
19  Interestingly I did not buy it for gaming purp...  4.7 out of 5
20  Fast response....no lag....light weight.....go...  4.7 out of 5
21  Microsoft Word documents are Not editable. Ver...    4 out of 5
22                                                  -             -
23  this review after use of 5 days.\n1. somebody ...  3.8 out of 5
24  Very impressed with the laptop. Looks extremel...    4 out of 5
25  Update:\nI don't know what's wrong with my bel...  4.2 out of 5
26  Received this yesterday (04/03/2021). Prompt d...  4.3 out of 5
27  Very impressed with the laptop. Looks extremel...    4 out of 5
28  I purchased the order on Jan 28th and got the ...  3.5 out of 5
29  Laptop is powerful and it's design looks cute ...  4.4 out of 5
30  Overall it's a good laptop. Just one thing abo...  4.1 out of 5
31  The upper part of the body looks goods but the...  3.8 out of 5
32  Specifications are good at this price.\nAnd bo...  4.2 out of 5
33  Not happy with the product , it's heating like...  3.7 out of 5
34  Battery backup is near about 3 Hour\n\nNo back...  4.1 out of 5
35    Best lap for normal use... budget friendly...🔥🔥    4 out of 5

In [19]:
#Findind the space bar
space_bar=driver.find_element_by_xpath('//div[@class="nav-search-field "]/input')
space_bar.clear()
space_bar.send_keys('mobile')

In [20]:
search_btn=driver.find_element_by_id('nav-search-submit-button')
search_btn.click()

In [21]:
# scrape all product urls
product_urls = []
start=0
end=18
for page in range(start,end):#for loop for scrapping 18 page
    url=driver.find_elements_by_xpath('//a[@class="a-link-normal a-text-normal"]')       #scraping urls
    for i in url:
        product_urls.append(i.get_attribute("href"))                        #appending the urls in product_urls list
    nxt_button=driver.find_element_by_xpath('//ul[@class="a-pagination"]/li[4]/a')     #scraping the list of buttons from the page
    nxt_button.click()
    time.sleep(2)
    
    #Make empty list
    Review=[]
    Rating=[]
    
for url in product_urls:
    driver.get(url)
    time.sleep(2)
    
    
    #Extracting Review from xpath
    try:
        review=driver.find_element_by_xpath('//div[@class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content"]')
        Review.append(review.text)
    except NoSuchElementException:
        Review.append("-")
    
    time.sleep(1)
    
    #Extracting Rating from xpath
    try:
        rating=driver.find_element_by_xpath('//span[@class="a-size-base a-nowrap"]/span')
        Rating.append(rating.text)
    except NoSuchElementException:
        Rating.append("-")
        
time.sleep(1)
#Make DataFrame
df1=pd.DataFrame({'Review':Review,'Rating':Rating})
df1.head(5)

                                              Review        Rating
0  Very disappointed with the overall performance...  4.1 out of 5
1  Dont buy this it is not worth for money. It is...  4.2 out of 5
2  Very disappointed with the overall performance...  4.1 out of 5
3  Don’t buy this product .\nImage quality is bel...  4.2 out of 5
4  I am not happy buy the mobile in amazon.\nWhat...  4.2 out of 5

In [37]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  399 non-null    object
 1   Rating  399 non-null    object
dtypes: object(2)
memory usage: 6.4+ KB

In [38]:
#Findind the space bar and searching for headphones`
space_bar=driver.find_element_by_xpath('//div[@class="nav-search-field "]/input')
space_bar.clear()
space_bar.send_keys('Headphones')
search_btn=driver.find_element_by_id('nav-search-submit-button')
search_btn.click()

In [39]:
# scrape all product urls(Headphones)
product_urls = []
start=0
end=18
for page in range(start,end):#for loop for scrapping 18 page
    url=driver.find_elements_by_xpath('//a[@class="a-link-normal a-text-normal"]')       #scraping urls
    for i in url:
        product_urls.append(i.get_attribute("href"))                        #appending the urls in product_urls list
    nxt_button=driver.find_element_by_xpath('//ul[@class="a-pagination"]/li[4]/a')     #scraping the list of buttons from the page
    nxt_button.click()
    time.sleep(2)
    
    #Make empty list
    Review=[]
    Rating=[]
    
for url in product_urls:
    driver.get(url)
    time.sleep(2)
    
    
    #Extracting Review from xpath
    try:
        review=driver.find_element_by_xpath('//div[@class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content"]')
        Review.append(review.text)
    except NoSuchElementException:
        Review.append("-")
    
    time.sleep(1)
    
    #Extracting Rating from xpath
    try:
        rating=driver.find_element_by_xpath('//span[@class="a-size-base a-nowrap"]/span')
        Rating.append(rating.text)
    except NoSuchElementException:
        Rating.append("-")
        
time.sleep(1)
#Make DataFrame
df2=pd.DataFrame({'Review':Review,'Rating':Rating})
df2.head(5)

                                              Review        Rating
0  These headphones work great for children. They...  4.4 out of 5
1                                                  -             -
2  This is my honest review after using it for 20...  4.2 out of 5
3  I have purchased this boat earphone few months...  4.1 out of 5
4  Guys, guys do not buy this product its a scam ...    4 out of 5

In [40]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  414 non-null    object
 1   Rating  414 non-null    object
dtypes: object(2)
memory usage: 6.6+ KB

In [41]:
#Findind the space bar and searching for Watches`
space_bar=driver.find_element_by_xpath('//div[@class="nav-search-field "]/input')
space_bar.clear()
space_bar.send_keys('Watches')
search_btn=driver.find_element_by_id('nav-search-submit-button')
search_btn.click()

In [42]:
# scrape all product urls(Watches)
product_urls = []
start=0
end=7
for page in range(start,end):#for loop for scrapping 7 page
    url=driver.find_elements_by_xpath('//a[@class="a-link-normal a-text-normal"]')       #scraping urls
    for i in url:
        product_urls.append(i.get_attribute("href"))                        #appending the urls in product_urls list
    nxt_button=driver.find_element_by_xpath('//ul[@class="a-pagination"]/li[4]/a')     #scraping the list of buttons from the page
    nxt_button.click()
    time.sleep(2)
    
    #Make empty list
    Review=[]
    Rating=[]
    
for url in product_urls:
    driver.get(url)
    time.sleep(2)
    
    
    #Extracting Review from xpath
    try:
        review=driver.find_element_by_xpath('//div[@class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content"]')
        Review.append(review.text)
    except NoSuchElementException:
        Review.append("-")
    
    time.sleep(1)
    
    #Extracting Rating from xpath
    try:
        rating=driver.find_element_by_xpath('//span[@class="a-size-base a-nowrap"]/span')
        Rating.append(rating.text)
    except NoSuchElementException:
        Rating.append("-")
        
time.sleep(1)
#Make DataFrame
df3=pd.DataFrame({'Review':Review,'Rating':Rating})
df3.head(5)

                                              Review        Rating
0                                                  -             -
1  The look is awesome. Exact copy of Casio G sho...  3.8 out of 5
2                                                  -    4 out of 5
3                                                  -             -
4  Product is nice in overall looking but make su...  4.2 out of 5

In [43]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  420 non-null    object
 1   Rating  420 non-null    object
dtypes: object(2)
memory usage: 6.7+ KB

In [44]:
#Findind the space bar and searching for Router`
space_bar=driver.find_element_by_xpath('//div[@class="nav-search-field "]/input')
space_bar.clear()
space_bar.send_keys('Router')
search_btn=driver.find_element_by_id('nav-search-submit-button')
search_btn.click()

In [45]:
# scrape all product urls(Router)
product_urls = []
start=0
end=18
for page in range(start,end):#for loop for scrapping 18 page
    url=driver.find_elements_by_xpath('//a[@class="a-link-normal a-text-normal"]')       #scraping urls
    for i in url:
        product_urls.append(i.get_attribute("href"))                        #appending the urls in product_urls list
    nxt_button=driver.find_element_by_xpath('//ul[@class="a-pagination"]/li[4]/a')     #scraping the list of buttons from the page
    nxt_button.click()
    time.sleep(2)
    
    #Make empty list
    Review=[]
    Rating=[]
    
for url in product_urls:
    driver.get(url)
    time.sleep(2)
    
    
    #Extracting Review from xpath
    try:
        review=driver.find_element_by_xpath('//div[@class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content"]')
        Review.append(review.text)
    except NoSuchElementException:
        Review.append("-")
    
    time.sleep(1)
    
    #Extracting Rating from xpath
    try:
        rating=driver.find_element_by_xpath('//span[@class="a-size-base a-nowrap"]/span')
        Rating.append(rating.text)
    except NoSuchElementException:
        Rating.append("-")
        
time.sleep(1)
#Make DataFrame
df4=pd.DataFrame({'Review':Review,'Rating':Rating})
df4.head(5)

                                              Review        Rating
0  Router stop working from 10.04.2019, sent to R...  4.2 out of 5
1  Always wanted a dual-band router without anten...  3.9 out of 5
2  Checked my 100mbps speed getting 100mbps downl...  4.4 out of 5
3  Package was half sealed by Amazon and on the t...  4.2 out of 5
4  Upgraded to the TP-Link C20 after doing a fair...  4.3 out of 5

In [46]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  418 non-null    object
 1   Rating  418 non-null    object
dtypes: object(2)
memory usage: 6.7+ KB

In [108]:
#Concatanating all the dataframe in single dataframe
df_cat=pd.concat([df,df1,df2,df3,df4],axis=0)
df_cat.head(5)

                                              Review        Rating
0  Received this yesterday (04/03/2021). Prompt d...  4.3 out of 5
1                                                  -             -
2  I bought this laptop with 8gb of ram and 256GB...  4.2 out of 5
3  The display cracked inside after 2 months and ...  4.2 out of 5
4  Laptop getting hang very much and very much sl...  3.9 out of 5

In [109]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2068 entries, 0 to 417
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  2068 non-null   object
 1   Rating  2068 non-null   object
dtypes: object(2)
memory usage: 48.5+ KB

In [111]:
#Exporting df to jupyter notebook 
df_cat.to_csv('df_cat.csv')

In [72]:
#Opening the HomePage Flipkart.com
url='https://www.flipkart.com/'
driver.get(url)

time.sleep(2)

In [33]:
search_bar=driver.find_element_by_xpath('//div[@class="_3OO5Xc"]/input')
search_bar.clear()
search_bar.send_keys('laptop')

In [34]:
search_btn=driver.find_element_by_xpath('//button[@class="L0Z3Pu"]')
search_btn.click()

In [35]:
# scrape all product (laptop) urls 
product_urls = []
start=0
end=21
for page in range(start,end):#for loop for scrapping 20 page
    url=driver.find_elements_by_xpath('//a[@class="_1fQZEK"]')       #scraping urls
    for i in url:
        product_urls.append(i.get_attribute("href"))                        #appending the urls in product_urls list
    nxt_btn=driver.find_element_by_xpath('//span[text()="Next"]')     #scraping the list of buttons from the page
    nxt_btn.click()
    time.sleep(2)
    
    #Make empty list
    Review=[]
    Rating=[]
    
for url in product_urls:
    driver.get(url)
    time.sleep(2)
    
    
    #Extracting Review from xpath
    try:
        review=driver.find_element_by_xpath('//div[@class="t-ZTKy"]')
        Review.append(review.text)
    except NoSuchElementException:
        Review.append("-")
    
    time.sleep(1)
    
    #Extracting Rating from xpath
    try:
        rating=driver.find_element_by_xpath('//div[@class="_3LWZlK _1BLPMq"]')
        Rating.append(rating.text)
    except NoSuchElementException:
        Rating.append("-")
        
time.sleep(1)
#Make DataFrame
df5=pd.DataFrame({'Review':Review,'Rating':Rating})
df5.head(5)

                                              Review Rating
0  I am happy with this product. Great packing or...      4
1  The best performing gaming laptop with a beaut...      5
2  Good Product\n\nYesterday Received my laptop a...      4
3  I was confused between asus and lenovo s145 la...      5
4  Good if you buy during Big Discount sale. Boug...      4

In [36]:
#Giving input as 'mobile' in flipkart.com
search_bar=driver.find_element_by_xpath('//div[@class="_3OO5Xc"]/input')
search_bar.clear()
search_bar.send_keys('mobile')

In [37]:
search_btn=driver.find_element_by_xpath('//button[@class="L0Z3Pu"]')
search_btn.click()

In [39]:
# scrape all product (laptop) urls 
product_urls = []
start=0
end=21
for page in range(start,end):#for loop for scrapping 21 page
    url=driver.find_elements_by_xpath('//a[@class="_1fQZEK"]')       #scraping urls
    for i in url:
        product_urls.append(i.get_attribute("href"))                        #appending the urls in product_urls list
    nxt_btn=driver.find_element_by_xpath('//span[text()="Next"]')     #scraping the list of buttons from the page
    nxt_btn.click()
    time.sleep(2)
    
    #Make empty list
    Review=[]
    Rating=[]
    
for url in product_urls:
    driver.get(url)
    time.sleep(2)
    
    
    #Extracting Review from xpath
    try:
        review=driver.find_element_by_xpath('//div[@class="t-ZTKy"]')
        Review.append(review.text)
    except NoSuchElementException:
        Review.append("-")
    
    time.sleep(1)
    
    #Extracting Rating from xpath
    try:
        rating=driver.find_element_by_xpath('//div[@class="_3LWZlK _1BLPMq"]')
        Rating.append(rating.text)
    except NoSuchElementException:
        Rating.append("-")
        
time.sleep(1)
#Make DataFrame
df6=pd.DataFrame({'Review':Review,'Rating':Rating})
df6.head(5)

                                              Review Rating
0                                       Good product      3
1  Really nice phone, delivery is so fast that's ...      5
2  Really nice phone, delivery is so fast that's ...      5
3  Very nice phone from realme . Loved it Camera ...      5
4  Very nice phone from realme . Loved it Camera ...      5

In [40]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 504 entries, 0 to 503
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  504 non-null    object
 1   Rating  504 non-null    object
dtypes: object(2)
memory usage: 8.0+ KB

In [41]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 504 entries, 0 to 503
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  504 non-null    object
 1   Rating  504 non-null    object
dtypes: object(2)
memory usage: 8.0+ KB

In [52]:
#Giving input as 'watches' in flipkart.com
search_bar=driver.find_element_by_xpath('//div[@class="_3OO5Xc"]/input')
search_bar.clear()
search_bar.send_keys('watches')
search_btn=driver.find_element_by_xpath('//button[@class="L0Z3Pu"]')
search_btn.click()

In [53]:
# scrape all product (laptop) urls 
product_urls = []
start=0
end=35
for page in range(start,end):#for loop for scrapping 35 page
    url=driver.find_elements_by_xpath('//a[@class="_2UzuFa"]')       #scraping urls
    for i in url:
        product_urls.append(i.get_attribute("href"))                        #appending the urls in product_urls list
    nxt_btn=driver.find_element_by_xpath('//span[text()="Next"]')     #scraping the list of buttons from the page
    nxt_btn.click()
    time.sleep(2)
    
    #Make empty list
    Review=[]
    Rating=[]
    
for url in product_urls:
    driver.get(url)
    time.sleep(2)
    
    
    #Extracting Review from xpath
    try:
        review=driver.find_element_by_xpath('//div[@class="_6K-7Co"]')
        Review.append(review.text)
    except NoSuchElementException:
        Review.append("-")
    
    time.sleep(1)
    
    #Extracting Rating from xpath
    try:
        rating=driver.find_element_by_xpath('//div[@class="_3LWZlK _1BLPMq _3B8WaH"]')
        Rating.append(rating.text)
    except NoSuchElementException:
        Rating.append("-")
        
time.sleep(1)
#Make DataFrame
df7=pd.DataFrame({'Review':Review,'Rating':Rating})
df7.head(5)

                                              Review Rating
0                                                  -      -
1  This watch was so so good,i love this so much ...      5
2  Watch is a awesome and beautiful colour black ...      5
3                                                  -      -
4  very good watch i feel better because this is ...      5

In [54]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  1400 non-null   object
 1   Rating  1400 non-null   object
dtypes: object(2)
memory usage: 22.0+ KB

In [3]:
import pandas as pd
df_cat=pd.read_csv('df_cat.csv')
df_cat.head()

   Unnamed: 0                                             Review        Rating
0           0  Received this yesterday (04/03/2021). Prompt d...  4.3 out of 5
1           1                                                  -             -
2           2  I bought this laptop with 8gb of ram and 256GB...  4.2 out of 5
3           3  The display cracked inside after 2 months and ...  4.2 out of 5
4           4  Laptop getting hang very much and very much sl...  3.9 out of 5

In [4]:
#Concatanating aff the dataframe in a single df
df=pd.concat([df_cat,df5,df6,df7],axis=0)
df.head()

NameError: name 'df5' is not defined

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4476 entries, 0 to 1399
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2068 non-null   float64
 1   Review      4475 non-null   object
 2   Rating      4476 non-null   object
dtypes: float64(1), object(2)
memory usage: 139.9+ KB

In [2]:
#Exporting Data 
df.to_csv('Rating_prediction')

NameError: name 'df' is not defined